language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t notwaving/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true notwaving/docker-react npm run test -- --coverage
