sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t notwaving/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true notwaving/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-543586549126"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
